### PR TITLE
Introduce notification features

### PR DESCRIPTION
**Pull request by yutakusuno**
@starrylight90 @akadambi12

## Overview
This is the implementation of the backend part of the notification service. As for push notifications, I have created `frontend/src/components/Firebase/` for testing to see them on web browsers. When integrating between the frontend and the backend, it can be utilized it if needed or deleted it.

## Technologies
| Push                           | Email                  | SMS        |
|--------------------------------|------------------------|------------|
| Firebase Cloud Messaging (FCM) | Gmail API, Nodemailer  | Twilio API | 

## Setup
See the documentation

## Testing

What I tested

- Three types of notifications can be sent using RabbitMQ
- Notification collections are updated as expected with three statuses 'pending', 'delivered', and 'failed'
- Retry process runs after transmission failure

See the documentation for load testing

### CODE REVIEW

**Comment by yutakusuno** [comment]
Sorry for the inconvenience, please reopen it. Even if I created a new PR, the PR that is still not merged seems to be closed automatically when the contributor deletes their forked repository.

**Review by starrylight90 — COMMENTED** [review]
Let me check

**Comment by starrylight90** [comment]
> Sorry for the inconvenience, please reopen it. Even if I created a new PR, the PR that is still not merged seems to be closed automatically when the contributor deletes their forked repository.

@yutakusuno as you have deleted the repository I have been unable to reopen the pull request. You will have to create the pull request yourself

**Comment by yutakusuno** [comment]
New PR is here https://github.com/projecthuman-repo/Lotus-Learning-WebApp/pull/114

**Pull request closed without merging**
